sudo: required

language: python
python:
  - "3.4"

services:
  - docker

jobs:
  include:
    - stage: Build Docker image 'ycmd'
      script:
        - make build
    # - stage: Test connection with example client
    #   script:
        - pip install httpie requests
        - make test

        # We set these via the Travis CI website.
        - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
        - make push
