sudo: required

services:
  - docker

jobs:
  include:
    - stage: Build Docker image 'ycmd'
      script:
        - make build
    - stage: Test connection with example client
      script:
        - make test
