sudo: required

language: python
python:
  - "3.4"

services:
  - docker

jobs:
  include:
    - stage: Build Docker image 'ycmd'
      script:
        - make image

        - pip install -r tests/requirements.txt
        - make test

        # We set these via the Travis CI website.
        - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin
        - make push
