sudo: required

language: python
python:
  - "3.4"

services:
  - docker

jobs:
  include:
    - stage: Build Docker image 'ycmd'
      script:
        - make build
    # - stage: Test connection with example client
    #   script:
        - pip install requests
        - make test
